server:
  port: 8082
  servlet:
    context-path: "/tenants"
spring:
  application:
    name: tenants-service
  cloud:
    consul:
      config:
        enabled: false
management:
  endpoints:
    web:
      exposure:
        include: info, health, prometheus, env, configprops, beans
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0
  metrics:
    distribution:
      percentiles-histogram:
        http:
          server:
            requests: true