version: '3.8'

services:
  kong-database:
    image: postgres:9.6
    container_name: kong-database
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=kong
      - POSTGRES_DB=kong
      - POSTGRES_PASSWORD=kong
    volumes:
      - "db-data-kong-postgres:/var/lib/postgresql/data"
    networks:
      ezpz-cluster:

  kong-migrations:
    image: kong
    environment:
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
    command: kong migrations bootstrap
    restart: on-failure
    depends_on:
      - kong-database
    networks:
      ezpz-cluster:

  kong:
    image: kong
    container_name: kong
    environment:
      - LC_CTYPE=en_US.UTF-8
      - LC_ALL=en_US.UTF-8
      - KONG_DATABASE=postgres
      - KONG_PG_HOST=kong-database
      - KONG_PG_USER=kong
      - KONG_PG_PASSWORD=kong
      - KONG_CASSANDRA_CONTACT_POINTS=kong-database
      - KONG_PROXY_ACCESS_LOG=/dev/stdout
      - KONG_ADMIN_ACCESS_LOG=/dev/stdout
      - KONG_PROXY_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_ERROR_LOG=/dev/stderr
      - KONG_ADMIN_LISTEN=0.0.0.0:8001, 0.0.0.0:8444 ssl
      - KONG_ADMIN_GUI_PATH=/manager
      - KONG_ADMIN_GUI_URL=http://localhost:8002/manager
    restart: on-failure
    ports:
      - 8000:8000
      - 8443:8443
      - 8001:8001
      - 8444:8444
      - 0.0.0.0:8002:8002
    links:
      - kong-database:kong-database
    depends_on:
      - kong-migrations
    networks:
      ezpz-cluster:

#  konga:
#    image: pantsel/konga
#    ports:
#      - 1337:1337
#    links:
#      - kong:kong
#    depends_on:
#      - kong
#    container_name: konga
#    environment:
#      - NODE_ENV=production
  consul: # Service Discovery
    image: hashicorp/consul:latest
    container_name: consul
    ports:
      - "8400:8400"
      - "8500:8500"
      - "8600:8600"
    networks:
      ezpz-cluster:
    command: 'agent -server -bootstrap-expect=1 -ui -bind=0.0.0.0 -client=0.0.0.0'
  mongo-server: # NoSQL Datastore
    image: mongo:latest
    container_name: 'mongo-server'
    restart: always
    labels:
      org.springframework.boot.service-connection: mongo-server
    ports:
      - '27017:27017'
    volumes:
      - mongo:/data/db
    networks:
      ezpz-cluster:

  tempo: # Metrics
    image: grafana/tempo:2.2.2
    container_name: tempo
    command: [ "-config.file=/etc/tempo.yml" ]
    volumes:
      - ./docker/tempo/tempo.yml:/etc/tempo.yml:ro
      - ./docker/tempo/tempo-data:/tmp/tempo
    ports:
      - "3110:3100"  # Tempo
      - "9411:9411" # zipkin
    networks:
      ezpz-cluster:
  loki: # Log aggregator
    image: grafana/loki:2.9.2
    container_name: loki
    ports:
      - "3100:3100"
    command: -config.file=/etc/loki/local-config.yaml
    networks:
      ezpz-cluster:
  prometheus: # Metrics DB
    image: prom/prometheus:v2.46.0
    container_name: prometheus
    command:
      - --enable-feature=exemplar-storage
      - --config.file=/etc/prometheus/prometheus.yml
    volumes:
      - ./docker/prometheus/prometheus.yml:/etc/prometheus/prometheus.yml:ro
    ports:
      - "9090:9090"
    networks:
      ezpz-cluster:
  grafana: # Dashboards
    image: grafana/grafana:10.1.0
    container_name: grafana
    volumes:
      - ./docker/grafana/datasources:/etc/grafana/provisioning/datasources:ro
      - ./docker/grafana/dashboards:/etc/grafana/provisioning/dashboards:ro
    environment:
      - GF_AUTH_ANONYMOUS_ENABLED=true
      - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
      - GF_AUTH_DISABLE_LOGIN_FORM=true
    ports:
      - "3000:3000"
    networks:
      ezpz-cluster:
  keycloak: # Identity Management System
    image: jboss/keycloak:latest
    restart: on-failure
    command:
      - "-b"
      - "0.0.0.0"
      - "-Dkeycloak.migration.action=import"
      - "-Dkeycloak.migration.provider=dir"
      - "-Dkeycloak.migration.dir=/config/"
      - "-Dkeycloak.migration.strategy=IGNORE_EXISTING"
    volumes:
      - ./config:/config/
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=password
      - DB_VENDOR=postgres
      - DB_USER=admin
      - DB_PASSWORD=password
      - DB_ADDR=keycloak-db
      - DB_PORT=5433
      - DB_DATABASE=keycloakdb
    ports:
      - "8090:8080"
    depends_on:
      - keycloak-db
    networks:
      ezpz-cluster:
  keycloak-db:
    image: postgres:16.0
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      POSTGRES_DB: keycloakdb
    ports:
      - "5433:5433"
    command: -p 5433
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      ezpz-cluster:

  website:
    image: ezpzapis/website
    container_name: website
    build: ./website
    restart: on-failure
    networks:
      ezpz-cluster:
    ports:
      - "3111:3111"

  tenants-service:
    image: 'ezpzapis/tenants-service'
    container_name: 'tenants-service'
    restart: on-failure
    ports:
      - '9991:8082'
    depends_on:
      - consul
      - mongo-server
      - loki
      - prometheus
      - grafana
      - tempo
    links:
      - consul
      - mongo-server
      - loki
      - prometheus
      - grafana
      - tempo
    environment:
      - spring.profiles.active=docker
      - spring.data.mongodb.host=mongo-server
      - spring.cloud.consul.host=consul
      - management.zipkin.tracing.endpoint=http://tempo:9411
      - LOKI_HOST=loki
    networks:
      ezpz-cluster:
  metastore-service:
    image: 'ezpzapis/metastore-service'
    container_name: 'metastore-service'
    restart: on-failure
    ports:
      - '9992:8081'
    networks:
      ezpz-cluster:
    links:
      - "consul"
    environment:
      - spring.profiles.active=docker
      - spring.cloud.consul.host=consul
      - spring.data.mongodb.host=mongo-server
      - spring.application.name=metastore-service
      #- server.port=8081
networks:
  ezpz-cluster:
volumes:
  pgdata:
  mongo:
    driver:
      local
  db-data-kong-postgres: