server:
  port: 8080
spring:
  application:
    name: api-gateway
  cloud:
    consul:
      config:
        enabled: false
    gateway:
      routes:
        - id: tenants-service
          uri: lb://tenants-service
          predicates:
            - Path=/api/tenants/**
          filters:
            - RewritePath=/api/tenants(?<path>.*), /$\{path}
        - id: metastore-service
          uri: lb://metastore-service
          predicates:
            - Path=/api/metastore/**
          filters:
            - RewritePath=/api/metastore(?<path>.*), /$\{path}
