global:
  scrape_interval: 2s
  evaluation_interval: 2s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['prometheus:9090']
  - job_name: 'krakend'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['krakend:9091'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'metastore-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['metastore-service:8081'] ## only for demo purposes don't use host.docker.internal in production
  - job_name: 'tenants-service'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: [ 'tenants-service:8082' ] ## only for demo purposes don't use host.docker.internal in production